@php
    $currentLocale = session('ui_locale', 'ar');
@endphp

<style>
    html[dir="ltr"] body { direction: ltr; text-align: left; }
    html[dir="ltr"] input,
    html[dir="ltr"] textarea,
    html[dir="ltr"] select { direction: ltr; text-align: left; }
    html[dir="ltr"] .page-header,
    html[dir="ltr"] .header { right: auto; left: 0; box-shadow: 10px 0 30px rgba(15, 23, 42, 0.15); }
    html[dir="ltr"] body:has(.page-header),
    html[dir="ltr"] body:has(.header) { padding-right: var(--page-gap, 40px); padding-left: calc(var(--sidebar-width, 240px) + var(--page-gap, 40px)); }
    html[dir="ltr"] .header-link,
    html[dir="ltr"] .home-button,
    html[dir="ltr"] .settings-button,
    html[dir="ltr"] nav a { text-align: left; }
    html[dir="ltr"] .customer-notice-dot,
    html[dir="ltr"] .nav-notice-dot { left: auto; right: 9px; }
    html[dir="ltr"] table th,
    html[dir="ltr"] table td { text-align: left; }
    @media (max-width: 980px) {
        html[dir="ltr"] body:has(.page-header),
        html[dir="ltr"] body:has(.header) { padding: 0; }
    }
</style>

<script>
    (() => {
        const locale = @json($currentLocale);
        const isEnglish = locale === 'en';

        document.documentElement.lang = isEnglish ? 'en' : 'ar';
        document.documentElement.dir = isEnglish ? 'ltr' : 'rtl';
        document.body?.classList.toggle('ui-ltr', isEnglish);

        if (!isEnglish) return;

        const dictionaryEntries = Object.entries({
            'الرئيسية': 'Home',
            'من نحن': 'About Us',
            'خدماتنا': 'Services',
            'كيف يعمل': 'How It Works',
            'تواصل معنا': 'Contact Us',
            'تسجيل الدخول': 'Login',
            'إنشاء حساب': 'Create Account',
            'إنشاء حساب جديد': 'Create New Account',
            'الصفحة الرئيسية': 'Home',
            'خدمات الطباعة والتجليد': 'Printing and Binding Services',
            'رقم الجوال أو البريد الإلكتروني': 'Phone Number or Email',
            'كلمة المرور': 'Password',
            'دخول': 'Login',
            'ليس لديك حساب؟': 'Do not have an account?',
            'العودة لتسجيل الدخول': 'Back to Login',
            'الاسم الأول': 'First Name',
            'الاسم الثاني': 'Second Name',
            'رقم الجوال': 'Phone Number',
            'البريد الإلكتروني': 'Email',
            'البريد الإلكتروني (اختياري)': 'Email (Optional)',
            'تأكيد كلمة المرور': 'Confirm Password',
            'إنشاء الحساب': 'Create Account',
            'لديك حساب بالفعل؟': 'Already have an account?',
            'القائمة': 'Menu',
            'طلباتي': 'My Orders',
            'إعداداتي': 'Settings',
            'تسجيل الخروج': 'Logout',
            'خروج': 'Logout',
            'لوحة المدير': 'Admin Panel',
            'الطلبات': 'Orders',
            'المستخدمين': 'Users',
            'العملاء': 'Customers',
            'الإعدادات': 'Settings',
            'اختر الخدمة المطلوبة': 'Choose the Required Service',
            'الدخول للخدمة': 'Open Service',
            'العودة للخدمات': 'Back to Services',
            'تحميل ملفات PDF': 'Upload PDF Files',
            'تحميل ملفات Word': 'Upload Word Files',
            'اختر ملفات': 'Choose Files',
            'ملفات PDF المحملة': 'Uploaded PDF Files',
            'ملفات Word المحملة': 'Uploaded Word Files',
            'اسم الملف': 'File Name',
            'الصفحات': 'Pages',
            'الحجم': 'Size',
            'النسخ': 'Copies',
            'نوع الطباعة': 'Print Type',
            'حجم الصفحة': 'Page Size',
            'التغليف': 'Binding',
            'التجليد': 'Binding',
            'سعر الطباعة': 'Printing Price',
            'سعر التغليف': 'Binding Price',
            'سعر التجليد': 'Binding Price',
            'الإجمالي': 'Total',
            'الحالة': 'Status',
            'حذف': 'Delete',
            'السلة والدفع': 'Cart and Payment',
            'الدفع': 'Payment',
            'Apple Pay': 'Apple Pay',
            'بطاقة بنكية': 'Bank Card',
            'اسم حامل البطاقة': 'Cardholder Name',
            'رقم البطاقة': 'Card Number',
            'تاريخ الانتهاء': 'Expiry Date',
            'دفع واعتماد الطلب': 'Pay and Confirm Order',
            'إغلاق': 'Close',
            'عرض الطلب': 'View Order',
            'إكمال الدفع': 'Complete Payment',
            'الفاتورة': 'Invoice',
            'الملفات المستلمة': 'Received Files',
            'تحميل': 'Download',
            'عرض': 'View',
            'حذف الطلب': 'Delete Order',
            'بياناتي': 'My Information',
            'بيانات العميل': 'Customer Information',
            'بيانات المستخدم': 'User Information',
            'حفظ التعديل': 'Save Changes',
            'تغيير كلمة المرور': 'Change Password',
            'كلمة المرور الجديدة': 'New Password',
            'تأكيد كلمة المرور الجديدة': 'Confirm New Password',
            'إضافة مستخدم': 'Add User',
            'إضافة عميل': 'Add Customer',
            'حفظ البريد': 'Save Email',
            'الصلاحيات': 'Permissions',
            'الحساب نشط': 'Account Active',
            'منع تسجيل الدخول': 'Block Login',
            'حساب موثق': 'Verified Account',
            'كود الخصم': 'Discount Code',
            'القيمة': 'Amount',
            'تطبيق الخصم': 'Apply Discount',
            'آخر الطلبات': 'Latest Orders',
            'عرض الكل': 'View All',
            'مؤشرات سريعة': 'Quick Indicators',
            'كل الطلبات': 'All Orders',
            'طلبات جديدة': 'New Orders',
            'قيد العمل': 'In Progress',
            'مكتملة': 'Completed',
            'المدفوع': 'Paid',
            'غير مدفوع': 'Unpaid',
            'رقم الطلب': 'Order ID',
            'العميل': 'Customer',
            'الخدمة': 'Service',
            'الدفع': 'Payment',
            'تاريخ الإنشاء': 'Created At',
            'الإجراء': 'Action',
            'حالة الدفع': 'Payment Status',
            'حالة الطلب': 'Order Status',
            'اللغة': 'Language',
            'العربية': 'Arabic',
            'English': 'English',
            'الورّاق منصة طلابية متخصصة في خدمات الطباعة والتجليد ورفع الملفات ومتابعة الطلبات إلكترونيًا.': 'Alwrraq is a student-focused platform for printing, binding, file uploads, and online order tracking.',
            'ابدأ الآن': 'Start Now',
            'طباعة الملفات': 'File Printing',
            'تجليد الرسائل العلمية': 'Academic Thesis Binding',
            'متابعة حالة الطلب': 'Order Tracking',
            'رفع الملفات إلكترونيًا': 'Online File Upload',
            'خدمات طلاب المدارس والجامعات': 'School and University Student Services',
            'سهولة الاستخدام': 'Easy to Use',
            'سرعة التنفيذ': 'Fast Processing',
            'حماية الملفات': 'File Protection',
            'متابعة الطلب': 'Order Tracking',
            'سياسة الخصوصية': 'Privacy Policy',
            'الشروط': 'Terms',
            'حقوق النشر': 'Copyright',
            'إحدى مؤسسات شركة مسير المدينة المحدودة': 'A division of Maseer Almadinah Limited Company',
            'طباعة المذكرات وملفات ال PDF': 'Black and White PDF Printing',
            'طباعة المذكرات وملفات PDF': 'Black and White PDF Printing',
            'طباعة الملفات بالألوان': 'Color File Printing',
            'طباعة وتجليد كتب كعب جلد طبيعي': 'Book Printing and Leather Spine Binding',
            'طباعة وتجليد رسالة ماجستير أو بحث تكميلي أو بحث تخرج': 'Master Thesis, Supplementary Research, or Graduation Project Printing and Binding',
            'طباعة وتجليد رسالة دكتوراه': 'PhD Thesis Printing and Binding',
            'تنسيق الرسائل الجامعية': 'Academic Thesis Formatting',
            'إنشاء بحث': 'Research Writing',
            'تدقيق لغوي': 'Proofreading',
            'تنسيق وتدقيق لغوي لرسائل الدكتوراه والماجستير': 'Formatting and Proofreading for Master and PhD Theses',
            'طباعة المذكرات والكتب': 'Notes and Book Printing',
            'تجليد الكتب كعب جلد طبيعي': 'Leather Spine Book Binding',
            'طباعة ابيض واسود': 'Black and White Printing',
            'طباعة أبيض وأسود': 'Black and White Printing',
            'طباعة ملفات PDF': 'PDF File Printing',
            'طباعة جميع المذكرات بجميع احجامها وتغليفها': 'Print and bind notes in all supported sizes',
            'طباعة ملفات ال PDF و الكتب بجيميع احجامها والتغليف وتجليد كعب جلد طبيعي': 'Print PDF files and books in all sizes with binding and leather spine binding',
            'تحميل ملفات مذكرات': 'Upload Notes Files',
            'تحميل ملفات الكتب': 'Upload Book Files',
            'تحميل ملفات الرسالة': 'Upload Thesis Files',
            'تحميل ملف Word': 'Upload Word File',
            'تحميل ملف PDF': 'Upload PDF File',
            'ملفات PDF المحملة': 'Uploaded PDF Files',
            'ملفات Word المحملة': 'Uploaded Word Files',
            'لم يتم تحميل أي ملفات': 'No files uploaded',
            'صيغ مدعومة:': 'Supported formats:',
            'حجم الملف:': 'File size:',
            'بدون حد أقصى': 'No maximum limit',
            'ملف PDF إجباري لإتمام الطلب.': 'A PDF file is required to complete the order.',
            'ملف Word للعرض أو للاستخدام لعمل الكعب والكليشة فقط، وليس للطباعه.': 'The Word file is for preview, spine, or cliche preparation only, not for printing.',
            'معلومة مهمة قبل رفع الملفات': 'Important note before uploading files',
            'يمكنك رفع أكثر من ملف داخل نفس الطلب، ويمكنك تكرار عدد النسخ لكل ملف حسب احتياجك.': 'You can upload more than one file in the same order and set the number of copies for each file as needed.',
            'اختر نوع التغليف لكل ملف لعرض السعر.': 'Choose the binding type for each file to show the price.',
            'اختر التجليد لكل ملف لعرض السعر.': 'Choose the binding type for each file to show the price.',
            'اكتب اسم البحث وعدد الصفحات لعرض الإجمالي.': 'Enter the research title and page count to show the total.',
            'نوع مشروع الرسالة': 'Thesis Project Type',
            'اختر نوع مشروع الرسالة': 'Choose Thesis Project Type',
            'رسالة ماجستير': 'Master Thesis',
            'بحث تكميلي': 'Supplementary Research',
            'بحث تخرج': 'Graduation Research',
            'الجامعة/المعهد': 'University / Institute',
            'اختر جامعتك': 'Choose Your University',
            'اختيار الجامعة اختياري': 'University selection is optional',
            'إذا لم تجد جامعتك أو معهدك أو مدرستك أدخلها يدويًا': 'If you cannot find your university, institute, or school, enter it manually',
            'احفظ الجهة التعليمية': 'Save Educational Institution',
            'لون الرسالة': 'Thesis Cover Color',
            'اختر لون الرسالة': 'Choose Cover Color',
            'لون الكتابة': 'Writing Color',
            'اختر لون الكتابة': 'Choose Writing Color',
            'لون الورق': 'Paper Color',
            'اختر لون الورق': 'Choose Paper Color',
            'أبيض': 'White',
            'أصفر': 'Yellow',
            'أسود': 'Black',
            'أزرق فاتح': 'Light Blue',
            'أزرق كحلي': 'Navy Blue',
            'الأخضر الداكن': 'Dark Green',
            'الأخضر الفاتح': 'Light Green',
            'العنابي': 'Burgundy',
            'البيج': 'Beige',
            'الأبيض': 'White',
            'كتابة باللون الذهبي': 'Gold Writing',
            'كتابة باللون الأسود': 'Black Writing',
            'وجه واحد': 'One-sided',
            'وجهين': 'Double-sided',
            'عدد النسخ': 'Number of Copies',
            'عدد الصفحات': 'Number of Pages',
            'تغليف دبوس': 'Staple Binding',
            'تغليف سلك': 'Wire Binding',
            'تغليف عادي': 'Regular Binding',
            'تغليف حراري': 'Thermal Lamination',
            'بدون تغليف': 'No Binding',
            'تجليد كعب جلد طبيعي': 'Natural Leather Spine Binding',
            'تجليد دبوس': 'Staple Binding',
            'تجليد سلك': 'Wire Binding',
            'تجليد عادي': 'Regular Binding',
            'بدون تجليد': 'No Binding',
            'التغليف الحراري يحسب على كل ورقة وليس صفحة.': 'Thermal lamination is calculated per sheet, not per page.',
            'سعر التنسيق': 'Formatting Price',
            'سعر إنشاء البحث': 'Research Writing Price',
            'إجمالي الملف': 'File Total',
            'إجمالي الطلب': 'Order Total',
            'إجمالي الطباعة': 'Printing Total',
            'إجمالي التغليف': 'Binding Total',
            'إجمالي التجليد': 'Binding Total',
            'قبل الخصم': 'Before Discount',
            'بعد الخصم': 'After Discount',
            'الخصم': 'Discount',
            'رسوم التوصيل': 'Delivery Fee',
            'الاستلام والتوصيل': 'Pickup and Delivery',
            'استلام من الفرع': 'Pickup from Branch',
            'توصيل داخل الجامعة الإسلامية': 'Delivery inside Islamic University',
            'توصيل داخل المدينة المنورة': 'Delivery inside Madinah',
            'خارج المدينة المنورة عبر RedBox': 'Outside Madinah via RedBox',
            'إذا كان طلبك فوق ٣٥ ريال فالتوصيل داخل الجامعة الإسلامية مجاني.': 'If your order is above 35 SAR, delivery inside Islamic University is free.',
            'رقم الوحدة': 'Unit Number',
            'رقم الدور': 'Floor Number',
            'رقم الغرفة': 'Room Number',
            'اسم المدينة': 'City Name',
            'اسم الحي': 'District Name',
            'اسم الشارع': 'Street Name',
            'رابط الموقع': 'Location Link',
            'رابط موقع البيت من Google Maps': 'Home Location Link from Google Maps',
            'حفظ التوصيل': 'Save Delivery',
            'تم حفظ طريقة التوصيل': 'Delivery method saved',
            'أدخل كود الخصم': 'Enter Discount Code',
            'حفظ': 'Save',
            'تعديل': 'Edit',
            'إلغاء': 'Cancel',
            'تأكيد': 'Confirm',
            'نعم': 'Yes',
            'لا': 'No',
            'بحث': 'Search',
            'ابحث': 'Search',
            'كل الحالات': 'All Statuses',
            'كل الخدمات': 'All Services',
            'بانتظار الدفع': 'Awaiting Payment',
            'قيد المراجعة': 'Under Review',
            'تم التسعير': 'Priced',
            'قيد التنفيذ': 'In Progress',
            'مكتمل': 'Completed',
            'منتهي': 'Completed',
            'ملغي': 'Cancelled',
            'مدفوع': 'Paid',
            'غير مدفوع': 'Unpaid',
            'لا توجد طلبات حتى الآن.': 'No orders yet.',
            'تفاصيل الطلب': 'Order Details',
            'تفاصيل الملفات': 'File Details',
            'الملفات والتفاصيل': 'Files and Details',
            'الأسعار': 'Prices',
            'اسم العميل': 'Customer Name',
            'نوع الخدمة': 'Service Type',
            'اليوم والتاريخ والوقت': 'Day, Date, and Time',
            'المبلغ': 'Amount',
            'عرض الملف': 'View File',
            'تحميل الملف': 'Download File',
            'طباعة الملف مباشرة': 'Print File Directly',
            'العودة لعرض الطلب': 'Back to Order View',
            'العودة للطلبات': 'Back to Orders',
            'معاينة الملف': 'File Preview',
            'المعاينة غير مدعومة لهذا النوع': 'Preview is not supported for this file type',
            'المعاينة المباشرة غير مدعومة لهذا النوع': 'Direct preview is not supported for this file type',
            'عرض الملف المرفوع داخل طلبك.': 'View the uploaded file inside your order.',
            'معاينة ملف الطلب والطباعة المباشرة.': 'Preview the order file and print directly.',
            'الطباعة المباشرة تفتح نافذة الطابعة من المتصفح. تأكد من ضبط الطابعة على نفس البيانات أعلاه، ولا تعتمد على لون الورق من أمر الطباعة.': 'Direct printing opens the browser print dialog. Make sure printer settings match the details above; paper color is not controlled by the print command.',
            'المتصفح منع فتح نافذة الطباعة. اسمح بالنوافذ المنبثقة ثم حاول مرة أخرى.': 'The browser blocked the print window. Allow pop-ups and try again.',
            'الملفات المستلمة من الإدارة': 'Files Received from Administration',
            'لا توجد ملفات مستلمة حتى الآن': 'No received files yet',
            'تحميل الفاتورة PDF': 'Download Invoice PDF',
            'فاتورة الطلب': 'Order Invoice',
            'بيانات الفاتورة': 'Invoice Details',
            'أمر الدفع': 'Payment Command',
            'راجع بيانات الدفع': 'Review Payment Details',
            'رقم الطلب:': 'Order ID:',
            'التاريخ:': 'Date:',
            'الإجمالي قبل الخصم:': 'Total Before Discount:',
            'الإجمالي بعد الخصم:': 'Total After Discount:',
            'لا يقبل إلا أرقام وحروف إنجليزية ورموز فقط.': 'Only English letters, numbers, and symbols are accepted.',
            'لا يقبل إلا أرقام إنجليزية فقط، وسيتم تحويل الأرقام العربية تلقائيًا.': 'Only English digits are accepted; Arabic digits will be converted automatically.',
            'رقم الجوال يبدأ بـ 05 ويتكون من 10 أرقام.': 'The phone number must start with 05 and contain 10 digits.',
            'يجب أن يكون البريد الإلكتروني بصيغة صحيحة.': 'Email must be in a valid format.',
            'تواصل مع خدمة العملاء': 'Contact Customer Support',
            'مسؤول خدمة العملاء': 'Customer Support Agent',
            'اكتب رسالتك': 'Write your message',
            'إرسال': 'Send',
            'المحادثات': 'Chats',
            'لا توجد محادثات': 'No chats',
            'الصورة العامة للتطبيق': 'Application Overview',
            'اختر الباقة الأنسب لاحتياجاتك': 'Choose the package that fits your needs',
            'إدارة الحسابات': 'Account Management',
            'الصلاحيات والأدوار': 'Permissions and Roles',
            'الملفات': 'Files',
            'الطباعة والتجليد': 'Printing and Binding',
            'المالية': 'Finance',
            'الإشعارات': 'Notifications',
            'التقييمات': 'Reviews',
            'التقارير': 'Reports',
            'السجل': 'Logs',
            'التحكم بالحساب': 'Account Control',
            'إعدادات عامة': 'General Settings',
            'إنشاء مستخدم جديد': 'Create New User',
            'تعديل بيانات المستخدم': 'Edit User Data',
            'حذف المستخدم': 'Delete User',
            'إيقاف الحساب مؤقتًا': 'Temporarily Disable Account',
            'تفعيل الحساب': 'Activate Account',
            'إعادة تعيين كلمة المرور': 'Reset Password',
            'تغيير رقم الجوال': 'Change Phone Number',
            'تغيير البريد الإلكتروني': 'Change Email',
            'توثيق الحساب': 'Verify Account',
            'مشاهدة جميع الطلبات': 'View All Orders',
            'تعديل الطلب': 'Edit Order',
            'قبول الطلب': 'Accept Order',
            'رفض الطلب': 'Reject Order',
            'تغيير حالة الطلب': 'Change Order Status',
            'مشاهدة الملفات': 'View Files',
            'حذف الملفات': 'Delete Files',
            'استبدال الملف': 'Replace File',
            'تغيير الأسعار': 'Change Prices',
            'إصدار فاتورة': 'Issue Invoice',
            'عدد الطلبات': 'Orders Count',
            'عدد المستخدمين': 'Users Count',
            'الإيرادات': 'Revenue',
            'أكثر الخدمات استخدامًا': 'Most Used Services',
            'تصدير Excel أو PDF': 'Export Excel or PDF',
            'حذف حسابي': 'Delete My Account'
        });

        dictionaryEntries.push(...Object.entries({
            'دخول': 'Sign In',
            'تسجيل الخروج': 'Sign Out',
            'خروج': 'Sign Out',
            'اختر الخدمة المطلوبة': 'Choose a Service',
            'الدخول للخدمة': 'Start Service',
            'ادخل رقم جوالك أو بريدك الإلكتروني وكلمة المرور للمتابعة.': 'Enter your phone number or email and password to continue.',
            'يقبل رقم الجوال أو البريد بحروف وأرقام إنجليزية ورموز البريد فقط، والأرقام العربية تتحول تلقائيًا إلى إنجليزية.': 'Phone or email accepts English letters, numbers, and email symbols only. Arabic digits are converted automatically.',
            'كلمة المرور تقبل الحروف الإنجليزية والأرقام والرموز فقط.': 'Password accepts English letters, numbers, and symbols only.',
            'اكتب الرقم بأي صيغة أرقام عربية أو إنجليزية، وسيتم تحويله تلقائيًا إلى أرقام إنجليزية.': 'You can type Arabic or English digits; Arabic digits will be converted automatically.',
            'البريد يقبل الحروف الإنجليزية والأرقام والرموز الخاصة بالبريد فقط.': 'Email accepts English letters, numbers, and email symbols only.',
            'اختياري: اختر جامعتك أو معهدك أو مدرستك من القائمة، وإذا لم تجدها اكتب اسمها كاملًا يدويًا وسيتم حفظه. إذا ما تبغى تضيفها اختر غير مهتم.': 'Optional: choose your university, institute, or school from the list. If you cannot find it, type the full name manually and it will be saved. Select Not Interested if you do not want to add it.',
            'غير مهتم': 'Not Interested',
            'جامعتك / معهدك / مدرستك': 'Your University / Institute / School',
            'اختيار من القائمة': 'Choose from the List',
            'ابحث داخل القائمة': 'Search within the list',
            'الجهة المختارة': 'Selected Institution',
            'إذا ما حصلت جامعتك / معهدك / مدرستك ادخلها يدويًا': 'If you cannot find your university, institute, or school, enter it manually.',
            'اختر من القائمة أو اكتب اسم الجهة هنا': 'Choose from the list or type the institution name here',
            'تم حفظ الجهة التعليمية': 'Educational institution saved',
            'ما لقينا نتيجة مطابقة. تقدر تحفظ الاسم اللي كتبته.': 'No matching result found. You can save the name you typed.',
            'استخدام:': 'Use:',

            'الورّاق منصة طلابية متخصصة في خدمات الطباعة والتجليد ورفع الملفات ومتابعة الطلبات إلكترونيًا.': 'Alwrraq is a professional student platform for printing, binding, file uploads, and online order tracking.',
            'طباعة الملفات': 'Document Printing',
            'تجليد الرسائل العلمية': 'Academic Thesis Binding',
            'متابعة حالة الطلب': 'Track Your Order',
            'رفع الملفات إلكترونيًا': 'Upload Files Online',
            'خدمات طلاب المدارس والجامعات': 'Services for School and University Students',
            'سهولة الاستخدام': 'Simple and Easy to Use',
            'سرعة التنفيذ': 'Fast Turnaround',
            'حماية الملفات': 'Secure File Handling',
            'طباعة المذكرات وملفات ال PDF': 'Black-and-White PDF and Notes Printing',
            'طباعة المذكرات وملفات PDF': 'Black-and-White PDF and Notes Printing',
            'طباعة الملفات بالألوان': 'Color Document Printing',
            'طباعة وتجليد كتب كعب جلد طبيعي': 'Book Printing with Natural Leather Spine Binding',
            'طباعة وتجليد رسالة ماجستير أو بحث تكميلي أو بحث تخرج': 'Master Thesis, Supplementary Research, and Graduation Project Printing and Binding',
            'طباعة وتجليد رسالة دكتوراه': 'PhD Dissertation Printing and Binding',
            'إنشاء بحث': 'Research Paper Writing',
            'تجليد الكتب كعب جلد طبيعي': 'Natural Leather Spine Book Binding',
            'طباعة ابيض واسود': 'Black-and-White Printing',
            'طباعة أبيض وأسود': 'Black-and-White Printing',
            'طباعة ملفات PDF': 'PDF Printing',
            'طباعة جميع المذكرات بجميع احجامها وتغليفها': 'Print and bind notes in all supported sizes.',
            'طباعة ملفات ال PDF و الكتب بجيميع احجامها والتغليف وتجليد كعب جلد طبيعي': 'Print PDF files and books in all supported sizes with binding and natural leather spine binding.',

            'اختر نوع مشروع الرسالة': 'Select Thesis Project Type',
            'اختر جامعتك': 'Select Your University',
            'اختر لون الرسالة': 'Select Cover Color',
            'اختر لون الكتابة': 'Select Writing Color',
            'اختر لون الورق': 'Select Paper Color',
            'تغليف حراري - يحسب على كل ورقة': 'Thermal Lamination - calculated per sheet',
            'توصيل داخل الجامعة الإسلامية': 'Delivery inside the Islamic University',
            'توصيل داخل المدينة المنورة': 'Delivery within Madinah',
            '30 ريال إلى أقرب نقطة شحن': '30 SAR to the nearest pickup point',
            'مجانًا للطلبات 35 ريال فأكثر': 'Free for orders of 35 SAR or more',
            'مجانًا': 'Free',
            '5 ريال': '5 SAR',
            '20 ريال': '20 SAR',
            '30 ريال': '30 SAR',

            'راجع بياناتك وعدّلها عند الحاجة.': 'Review your information and update it when needed.',
            'لم تتم الإضافة بعد': 'Not added yet',
            'تعديل بياناتي': 'Edit My Information',
            'حفظ بياناتي': 'Save My Information',
            'عنواني': 'My Address',
            'الدولة': 'Country',
            'المملكة العربية السعودية': 'Saudi Arabia',
            'المدينة أو المحافظة': 'City or Governorate',
            'الرمز البريدي': 'Postal Code',
            'تعديل عنواني': 'Edit My Address',
            'إضافة عنواني': 'Add My Address',
            'اكتب للبحث ثم اختر المدينة': 'Type to search, then select the city',
            'اسم الحي': 'District Name',
            'حفظ العنوان': 'Save Address',
            'يمكنك تغيير كلمة المرور عند الحاجة.': 'You can change your password when needed.',
            'اكتب كلمة المرور القديمة ثم كلمة المرور الجديدة.': 'Enter your old password, then the new password.',
            'كلمة المرور القديمة': 'Old Password',
            'حفظ كلمة المرور': 'Save Password',
            'يمكنك حذف حسابك نهائيًا عند الحاجة.': 'You can permanently delete your account if needed.',
            'هل أنت متأكد من حذف حسابك نهائيًا؟': 'Are you sure you want to permanently delete your account?',

            'راجع الطلب قبل الدفع. لا يوجد دفع عند الاستلام أو كاش.': 'Review your order before payment. Cash on delivery is not available.',
            'أمر الدفع': 'Payment',
            'اختر طريقة الاستلام أو التوصيل ثم اضغط حفظ.': 'Choose pickup or delivery, then click Save.',
            'حفظ طريقة التوصيل': 'Save Delivery Method',
            'اختر طريقة الاستلام أو التوصيل أولًا.': 'Choose pickup or delivery first.',
            'اكتب رقم الوحدة ورقم الدور ورقم الغرفة.': 'Enter the unit number, floor number, and room number.',
            'اكتب اسم الحي والشارع وأضف رابط موقعك من Google Maps.': 'Enter the district, street, and your Google Maps location link.',
            'اكتب اسم المدينة والحي والشارع وأضف رابط موقعك من Google Maps.': 'Enter the city, district, street, and your Google Maps location link.',
            'خيار خارج المدينة لا يقبل المدينة المنورة. اكتب اسم المدينة خارج المدينة المنورة.': 'Outside Madinah delivery cannot use Madinah as the city. Enter a city outside Madinah.',
            'تعذر حفظ طريقة التوصيل': 'Could not save the delivery method.',
            'تعذر تطبيق كود الخصم': 'Could not apply the discount code.',
            'اكتب كود الخصم': 'Enter discount code',
            'اكتب كود الخصم أولًا.': 'Enter the discount code first.',

            'ارفع الملفات لعرض الإجمالي.': 'Upload files to show the total.',
            'اختر نوع التغليف لكل ملف قبل إتمام الطلب.': 'Select the binding type for each file before completing the order.',
            'ارفع ملف PDF لإتمام الطلب وعرض الإجمالي.': 'Upload a PDF file to complete the order and show the total.',
            'اختر نوع مشروع الرسالة لكل ملف PDF قبل إتمام الطلب.': 'Select the project type for each PDF file before completing the order.',
            'اختر لون الرسالة ولون الكتابة لكل ملف قبل إتمام الطلب.': 'Select the cover color and writing color for each file before completing the order.',
            'الكتابة باللون الأسود متاحة فقط مع البيج أو الأزرق الفاتح أو الأخضر الفاتح أو الأبيض.': 'Black writing is only available with beige, light blue, light green, or white covers.',
            'ارفع ملفات Word لعرض الإجمالي.': 'Upload Word files to show the total.',
            'اكتب اسم البحث المطلوب أولًا.': 'Enter the research title first.',
            'حدد عدد الصفحات المطلوبة.': 'Enter the required number of pages.',
            'احفظ الطلب أولًا': 'Save the order first',
            'اكتب اسم البحث وحدد عدد الصفحات بالأرقام الإنجليزية فقط.': 'Enter the research title and page count using English digits only.',
            'جاري الحفظ...': 'Saving...',
            'تعذر حفظ طلب إنشاء البحث': 'Could not save the research writing order.',
            'مشروع الرسالة': 'Thesis Project',
            'اختر المشروع': 'Select Project',
            'الكتابة السوداء لا تناسب هذا اللون': 'Black writing is not suitable for this color.',
            'اختر الألوان': 'Select colors',
            'صفحة': 'page',
            'مرفوع': 'Uploaded',
            'صيغة غير صحيحة': 'Invalid file format',
            'تعذر تحميل الملف': 'Could not upload the file.',
            'تعذر الاتصال بالخادم أثناء تحميل الملف': 'Could not connect to the server while uploading the file.',
            'منصة متخصصة في خدمات الطباعة والتجليد للمذكرات والأبحاث والرسائل العلمية.': 'A specialized platform for printing and binding notes, research papers, and academic theses.',
            'جميع الحقوق محفوظة.': 'All rights reserved.',
            'مذكرات': 'Notes',
            'كتب': 'Books',
            'ماجستير': 'Master Thesis',
            'دكتوراه': 'PhD Dissertation',
            'الملفات': 'Files',
            'تطبيق': 'Apply',
            'كود الخصم قبل الدفع': 'Discount Code Before Payment',
            'تم تطبيق': 'Applied',
            'خصم': 'Discount',
            'السلة': 'Cart',
            'هل تريد حذف هذا الطلب وجميع ملفاته؟': 'Do you want to delete this order and all its files?',
            'ملفات لم يتم تحميلها': 'Files not downloaded yet',
            'اختيار نوع التغليف لكل ملف.': 'Select the binding type for each file.',
            'اختيار لون الرسالة ولون الكتابة لكل ملف.': 'Select the cover color and writing color for each file.',
            'اختيار نوع مشروع الرسالة لكل ملف PDF.': 'Select the project type for each PDF file.',
            'اضغط عرض الطلب للتفاصيل': 'Click View Order for details',
            'الأحد': 'Sunday',
            'الاثنين': 'Monday',
            'الثلاثاء': 'Tuesday',
            'الأربعاء': 'Wednesday',
            'الخميس': 'Thursday',
            'الجمعة': 'Friday',
            'السبت': 'Saturday',
            'بدون أي تغليف': 'No Binding',
            'اختر التغليف': 'Select Binding',
            'اختياري: اختر أو اكتب الجامعة/المعهد': 'Optional: select or type the university/institute',
            'انسخ رابط موقعك من Google Maps': 'Paste your location link from Google Maps',
            'تنبيه: إذا طلبك فوق 35 ريال يكون التوصيل داخل الجامعة الإسلامية مجانًا.': 'Note: Delivery inside the Islamic University is free for orders above 35 SAR.',
            'تم حفظ طريقة التوصيل. الرسوم:': 'Delivery method saved. Fee:',
            'خدمات الطباعة والتجليد.': 'Printing and binding services.',
            'خدمات الطباعة والتجليد': 'Printing and Binding Services',
            'جاري التحميل...': 'Loading...',
            'لا توجد نتائج': 'No results',
            'لا توجد بيانات': 'No data available',
            'لا يوجد': 'None',
            'اختياري': 'Optional',
            'مطلوب': 'Required',
            'تنبيه: تسجيل الدخول يقبل الحروف الإنجليزية والأرقام والرموز فقط.': 'Notice: Sign in accepts English letters, numbers, and symbols only.',
            'تنبيه: رقم الجوال يجب أن يبدأ بـ 05 ويتكون من 10 أرقام إنجليزية فقط.': 'Notice: The phone number must start with 05 and contain exactly 10 English digits.',
            'تنبيه: اكتب بريدًا إلكترونيًا صحيحًا مثل name@example.com.': 'Notice: Enter a valid email address such as name@example.com.',
            'تنبيه: كلمة المرور تقبل الحروف الإنجليزية والأرقام والرموز فقط.': 'Notice: Password accepts English letters, numbers, and symbols only.',
            'تنبيه: كلمة المرور تقبل حروف وأرقام إنجليزية فقط.': 'Notice: Password accepts English letters and numbers only.',
            'تنبيه: لا يقبل هذا الحقل إلا الأرقام الإنجليزية فقط 0-9.': 'Notice: This field accepts English digits only, 0-9.',
            'تنبيه: رقم البطاقة يقبل الأرقام الإنجليزية والمسافات فقط.': 'Notice: Card number accepts English digits and spaces only.',
            'تنبيه: اكتب تاريخ الانتهاء بالأرقام الإنجليزية بصيغة MM/YY.': 'Notice: Enter the expiry date using English digits in MM/YY format.',
            'تنبيه: كود الخصم يقبل حروف وأرقام إنجليزية فقط.': 'Notice: Discount code accepts English letters and numbers only.',
            'استخدم الأرقام الإنجليزية فقط 0-9.': 'Use English digits only, 0-9.',
            'تنبيه: عند اختيار وجهين يتم حساب كل ورقتين بقيمة ورقة واحدة في التغليف الحراري.': 'Notice: With double-sided printing, each two pages are counted as one sheet for thermal lamination.',
            'تنبيه: التغليف الحراري يحسب على كل ورقة لحالها.': 'Notice: Thermal lamination is calculated for each sheet separately.',
            'اكتب بريدًا إلكترونيًا صحيحًا مثل name@example.com': 'Enter a valid email address such as name@example.com'
            ,
            'روابط الصفحة': 'Page Links',
            'خدمات طباعة وتجليد للطلاب': 'Printing and Binding Services for Students',
            'الورّاق لإدارة طلبات الطباعة ورفع الملفات بسهولة': 'Alwrraq Makes Print Orders and File Uploads Simple',
            'منصة تساعد الطلاب على رفع ملفاتهم، اختيار إعدادات الطباعة والتجليد، مراجعة الطلب، إكمال الدفع، ومتابعة حالة الطلب من مكان واحد.': 'A platform that helps students upload files, choose printing and binding options, review orders, complete payment, and track order status from one place.',
            'مميزات مختصرة': 'Quick Highlights',
            'رفع إلكتروني': 'Online Upload',
            'ملفاتك داخل حسابك': 'Your files stay in your account',
            'متابعة مباشرة': 'Live Tracking',
            'حالة الطلب والفاتورة': 'Order status and invoice',
            'خيارات دقيقة': 'Detailed Options',
            'طباعة وتجليد وتوصيل': 'Printing, binding, and delivery',
            'ملخص الخدمات': 'Services Summary',
            'كل طلبك في خطوات واضحة': 'Your Entire Order in Clear Steps',
            'رفع ملفات PDF و Word حسب نوع الخدمة.': 'Upload PDF and Word files depending on the selected service.',
            'اختيار النسخ، حجم الصفحة، الطباعة، والتجليد.': 'Choose copies, page size, printing type, and binding.',
            'متابعة الطلب والفواتير والملفات المستلمة.': 'Track orders, invoices, and received files.',
            'الورّاق تجربة طلابية متكاملة بخدمة موثوقة وتنفيذ منظم': 'Alwrraq: A Complete Student Experience with Reliable Service and Organized Fulfillment',
            'الورّاق منصة متخصصة في تسهيل خدمات الطباعة والتجليد ورفع الملفات ومتابعة الطلبات للطلاب، صممت لتجمع بين وضوح الإجراءات وسرعة التنفيذ وحفظ تفاصيل الطلب في مكان واحد. نحن إحدى مؤسسات شركة مسير المدينة المحدودة، ونعمل على تقديم تجربة رقمية مرتبة تساعد الطالب على إنجاز طلبه بثقة وراحة من لحظة رفع الملف حتى استلامه.': 'Alwrraq is a specialized platform that simplifies printing, binding, file upload, and order tracking for students. It is designed to combine clear steps, fast processing, and organized order details in one place. We are one of the entities under Maseer Almadinah Limited Company, providing a structured digital experience that helps students complete their orders confidently from file upload to delivery.',
            'قيم الورّاق': 'Alwrraq Values',
            'خدمة مبنية على احتياج الطالب': 'A Service Built Around Student Needs',
            'نركز على جعل خطوات الطلب واضحة، مختصرة، وسهلة المتابعة.': 'We focus on making order steps clear, concise, and easy to track.',
            'تنظيم يحفظ التفاصيل': 'Organized Details',
            'كل ملف وخيار وسعر وحالة طلب تظهر للعميل بطريقة مباشرة.': 'Every file, option, price, and order status is shown clearly to the customer.',
            'هوية مهنية موثوقة': 'Trusted Professional Identity',
            'نعمل تحت مظلة شركة مسير المدينة المحدودة لتقديم خدمة أكثر استقرارًا وجودة.': 'We operate under Maseer Almadinah Limited Company to provide a more stable and higher-quality service.',
            'معاينة واجهات الورّاق': 'Alwrraq Interface Preview',
            'واجهة تعمل على الجوال والكمبيوتر': 'Works on Mobile and Desktop',
            'تجربة واحدة مرتبة من تسجيل الدخول حتى متابعة الطلب': 'One Organized Experience from Sign In to Order Tracking',
            'صممنا واجهات الورّاق لتظهر تفاصيل الخدمة والملفات والأسعار والطلبات بوضوح، سواء استخدمها الطالب من الجوال أو من شاشة الكمبيوتر.': 'Alwrraq interfaces are designed to show service details, files, prices, and orders clearly on both mobile and desktop screens.',
            'تحميل ملف PDF إجباري + ملف Word للكعب والكليشة': 'Required PDF file + Word file for spine and cliche',
            '126 صفحة': '126 pages',
            'نسختان': 'Two copies',
            'لون الرسالة: كحلي': 'Cover color: Navy',
            'لون الكتابة: ذهبي': 'Writing color: Gold',
            'التجليد: جلد طبيعي': 'Binding: Natural leather',
            'الإجمالي قبل التوصيل': 'Total before delivery',
            '240 ريال': '240 SAR',
            'أبيض وأسود، أحجام، تغليف': 'Black and white, sizes, binding',
            'A4 / A3 وتغليف حراري': 'A4 / A3 and thermal lamination',
            'كتب وملازم وتجليد احترافي': 'Books, booklets, and professional binding',
            'ألوان رسالة وكتابة وتجليد': 'Cover colors, writing, and binding',
            'PDF للطباعة و Word للكعب': 'PDF for printing and Word for spine',
            'Word وخدمة تسليم داخل الطلبات': 'Word file and delivery inside orders',
            'اكتب عنوان البحث وعدد الصفحات': 'Enter research title and page count',
            'مجموعة خدمات أكاديمية وطباعية متكاملة تخدم طلاب المدارس والجامعات والباحثين.': 'A complete set of academic and printing services for school students, university students, and researchers.',
            'تنسيق رسائل الدكتوراه والماجستير': 'Master and PhD Thesis Formatting',
            'خدمة تنسيق أكاديمي للرسائل الجامعية مع متابعة تسليم الملف بعد الانتهاء.': 'Academic thesis formatting with delivery tracking after completion.',
            'تدقيق لغوي للرسائل العلمية': 'Academic Proofreading',
            'مراجعة لغوية احترافية لرسائل الدكتوراه والماجستير والبحوث الأكاديمية.': 'Professional proofreading for PhD theses, master theses, and academic research.',
            'طباعة وتجليد رسائل الماجستير': 'Master Thesis Printing and Binding',
            'خيارات مخصصة للطباعة والتجليد وألوان الرسالة والكتابة حسب متطلباتك.': 'Custom printing, binding, cover color, and writing color options based on your requirements.',
            'طباعة وتجليد رسائل الدكتوراه': 'PhD Dissertation Printing and Binding',
            'تجهيز رسائل الدكتوراه بملفات PDF للطباعة وملفات Word للكعب والكليشة.': 'Prepare PhD dissertations with PDF files for printing and Word files for spine and cliche.',
            'إنشاء البحوث': 'Research Writing',
            'إرسال عنوان البحث وعدد الصفحات المطلوبة ومتابعة تسليم الملف داخل حسابك.': 'Send the research title and required page count, then track file delivery inside your account.',
            'طباعة المذكرات والكتب': 'Notes and Book Printing',
            'طباعة ملفات PDF والمذكرات والكتب بخيارات حجم الورق والنسخ والتغليف.': 'Print PDF files, notes, and books with paper size, copy count, and binding options.',
            'تجليد الكتب كعب جلد طبيعي': 'Natural Leather Spine Book Binding',
            'تجليد كتب وملازم بكعب جلد طبيعي وبمقاسات مناسبة للكتب الدراسية والأكاديمية.': 'Bind books and booklets with natural leather spines in sizes suitable for academic materials.',
            'طباعة الملفات بالألوان': 'Color Document Printing',
            'طباعة ملونة بمقاسات متعددة وخيارات تغليف حراري حسب نوع الملف والاستخدام.': 'Color printing in multiple sizes with thermal lamination options depending on file type and use.',
            'رفع الملفات ومتابعة الطلب': 'File Upload and Order Tracking',
            'رفع الملفات إلكترونيًا، مراجعة تفاصيل الطلب، الفاتورة، وحالة التنفيذ من حسابك.': 'Upload files online, review order details, invoices, and processing status from your account.',
            'كيف يعمل الورّاق؟': 'How Does Alwrraq Work?',
            'خطوات بسيطة من إنشاء الحساب حتى متابعة الطلب.': 'Simple steps from account creation to order tracking.',
            'أنشئ حسابًا أو سجل الدخول': 'Create an Account or Sign In',
            'ابدأ بحسابك للوصول إلى الخدمات.': 'Start with your account to access services.',
            'ارفع ملفاتك': 'Upload Your Files',
            'أضف ملفًا أو أكثر داخل الطلب.': 'Add one or more files inside the order.',
            'اختر الإعدادات': 'Choose Settings',
            'حدد الطباعة والتجليد والعدد.': 'Select printing, binding, and quantity.',
            'راجع الطلب وأكمل الدفع': 'Review the Order and Complete Payment',
            'تأكد من الإجمالي وأكمل العملية.': 'Check the total and complete the process.',
            'تابع حالة الطلب': 'Track Order Status',
            'راجع طلباتك والملفات المستلمة.': 'Review your orders and received files.',
            'مميزات المنصة': 'Platform Features',
            'تجربة مرتبة وآمنة لإدارة طلباتك.': 'An organized and secure experience for managing your orders.',
            'واجهة واضحة من رفع الملف حتى الطلب.': 'A clear interface from file upload to order submission.',
            'تجهيز الطلبات ببيانات واضحة ومباشرة.': 'Prepare orders with clear and direct information.',
            'ملفاتك تظهر داخل حسابك فقط.': 'Your files are visible only inside your account.',
            'تعرف على حالة الطلب والفواتير بسهولة.': 'Easily view order status and invoices.',
            'للاستفسارات أو المساعدة في الطلبات، يمكنك تسجيل الدخول ومتابعة طلبك من داخل حسابك.': 'For inquiries or order help, sign in and follow your order from your account.',
            'الدخول لحسابك': 'Sign In to Your Account',
            'الشروط والأحكام': 'Terms and Conditions'
        }));

        const dictionary = new Map(dictionaryEntries);
        const phraseEntries = dictionaryEntries
            .filter(([arabic]) => /[\u0600-\u06FF]/.test(arabic) && arabic.length >= 10)
            .sort((a, b) => b[0].length - a[0].length);
        const safeInlineEntries = [
            ['حذف حسابي', 'Delete My Account'],
            ['حذف الحساب', 'Delete Account'],
            ['حسابي', 'My Account'],
            ['حساب', 'Account'],
            ['تعديل بياناتي', 'Edit My Information'],
            ['تعديل البيانات', 'Edit Information'],
            ['حفظ البيانات', 'Save Information'],
            ['حفظ بياناتي', 'Save My Information'],
            ['بياناتي', 'My Information'],
            ['بيانات', 'Information'],
            ['تسجيل الخروج', 'Sign Out'],
            ['إنشاء حساب جديد', 'Create New Account'],
            ['إنشاء الحساب', 'Create Account'],
            ['إنشاء حساب', 'Create Account'],
            ['تسجيل الدخول', 'Sign In'],
            ['الصفحة الرئيسية', 'Home'],
            ['القائمة', 'Menu'],
            ['الرئيسية', 'Home'],
            ['من نحن', 'About Us'],
            ['خدماتنا', 'Services'],
            ['كيف يعمل', 'How It Works'],
            ['تواصل معنا', 'Contact Us'],
            ['طلباتي', 'My Orders'],
            ['إعداداتي', 'Settings'],
            ['الإعدادات', 'Settings'],
            ['الطلبات', 'Orders'],
            ['المستخدمين', 'Users'],
            ['العملاء', 'Customers'],
            ['الصلاحيات', 'Permissions'],
            ['الدور', 'Role'],
            ['الحساب نشط', 'Account Active'],
            ['منع تسجيل الدخول', 'Block Login'],
            ['حساب موثق', 'Verified Account'],
            ['الفاتورة', 'Invoice'],
            ['السلة والدفع', 'Cart and Payment'],
            ['السلة', 'Cart'],
            ['الدفع', 'Payment'],
            ['الخدمة', 'Service'],
            ['الملفات', 'Files'],
            ['الملف', 'File'],
            ['نوع الملف', 'File Type'],
            ['نوع الخدمة', 'Service Type'],
            ['نوع الطباعة', 'Print Type'],
            ['حجم الصفحة', 'Page Size'],
            ['لون الورق', 'Paper Color'],
            ['لون الرسالة', 'Cover Color'],
            ['لون الكتابة', 'Writing Color'],
            ['مشروع الرسالة', 'Thesis Project'],
            ['نوع مشروع الرسالة', 'Thesis Project Type'],
            ['اسم الملف', 'File Name'],
            ['الحجم', 'Size'],
            ['النسخ', 'Copies'],
            ['الصفحات', 'Pages'],
            ['الحالة', 'Status'],
            ['الإجراء', 'Action'],
            ['حالة الدفع', 'Payment Status'],
            ['حالة الطلب', 'Order Status'],
            ['رقم الطلب', 'Order ID'],
            ['اسم العميل', 'Customer Name'],
            ['بيانات العميل', 'Customer Information'],
            ['بيانات المستخدم', 'User Information'],
            ['بيانات المدير', 'Admin Information'],
            ['مدير النظام', 'System Admin'],
            ['مسؤول خدمة العملاء', 'Customer Support'],
            ['خدمة العملاء', 'Customer Support'],
            ['الاسم الأول', 'First Name'],
            ['الاسم الثاني', 'Second Name'],
            ['رقم الجوال', 'Phone Number'],
            ['البريد الإلكتروني', 'Email'],
            ['كلمة المرور', 'Password'],
            ['كلمة المرور القديمة', 'Old Password'],
            ['كلمة المرور الجديدة', 'New Password'],
            ['تأكيد كلمة المرور', 'Confirm Password'],
            ['تأكيد كلمة المرور الجديدة', 'Confirm New Password'],
            ['تغيير كلمة المرور', 'Change Password'],
            ['حفظ كلمة المرور', 'Save Password'],
            ['اكتب الاسم أو رقم الجوال', 'Search by name or phone number'],
            ['الاسم أو رقم الجوال', 'Name or Phone Number'],
            ['الاسم', 'Name'],
            ['نص عربي فقط', 'Letters only'],
            ['ادخل نص عربي فقط', 'Enter letters only'],
            ['أدخل نص عربي فقط', 'Enter letters only'],
            ['العنوان', 'Address'],
            ['عنواني', 'My Address'],
            ['الدولة', 'Country'],
            ['المدينة', 'City'],
            ['المدينة أو المحافظة', 'City or Governorate'],
            ['الحي', 'District'],
            ['الشارع', 'Street'],
            ['الرمز البريدي', 'Postal Code'],
            ['اسم المدينة', 'City Name'],
            ['اسم الحي', 'District Name'],
            ['اسم الشارع', 'Street Name'],
            ['رابط الموقع', 'Location Link'],
            ['رقم الوحدة', 'Unit Number'],
            ['رقم الدور', 'Floor Number'],
            ['رقم الغرفة', 'Room Number'],
            ['التوصيل', 'Delivery'],
            ['الاستلام', 'Pickup'],
            ['الاستلام والتوصيل', 'Pickup and Delivery'],
            ['استلام من الفرع', 'Pickup from Branch'],
            ['رسوم التوصيل', 'Delivery Fee'],
            ['كود الخصم', 'Discount Code'],
            ['تطبيق الخصم', 'Apply Discount'],
            ['قبل الخصم', 'Before Discount'],
            ['بعد الخصم', 'After Discount'],
            ['الخصم', 'Discount'],
            ['القيمة', 'Amount'],
            ['المبلغ', 'Amount'],
            ['المبلغ الإجمالي', 'Total Amount'],
            ['الإجمالي قبل الخصم', 'Total Before Discount'],
            ['الإجمالي بعد الخصم', 'Total After Discount'],
            ['تاريخ الإنشاء', 'Created On'],
            ['التاريخ', 'Date'],
            ['اليوم', 'Day'],
            ['الوقت', 'Time'],
            ['اليوم والتاريخ والوقت', 'Day, Date, and Time'],
            ['التفاصيل', 'Details'],
            ['تفاصيل الطلب', 'Order Details'],
            ['تفاصيل الملفات', 'File Details'],
            ['الملفات والتفاصيل', 'Files and Details'],
            ['الأسعار', 'Prices'],
            ['الفاتوره', 'Invoice'],
            ['فاتورة الطلب', 'Order Invoice'],
            ['تحميل الفاتورة PDF', 'Download Invoice PDF'],
            ['الملفات المستلمة', 'Received Files'],
            ['الملفات المستلمة من الإدارة', 'Files Received from Administration'],
            ['لا توجد ملفات مستلمة حتى الآن', 'No received files yet'],
            ['إكمال الدفع', 'Complete Payment'],
            ['دفع واعتماد الطلب', 'Pay and Confirm Order'],
            ['حذف الطلب', 'Delete Order'],
            ['عرض الطلب', 'View Order'],
            ['عرض الملف', 'View File'],
            ['تحميل الملف', 'Download File'],
            ['طباعة الملف مباشرة', 'Print File Directly'],
            ['العودة للطلبات', 'Back to Orders'],
            ['العودة للخدمات', 'Back to Services'],
            ['العودة لتسجيل الدخول', 'Back to Sign In'],
            ['العودة لعرض الطلب', 'Back to Order View'],
            ['تحميل', 'Download'],
            ['عرض', 'View'],
            ['حذف', 'Delete'],
            ['تعديل', 'Edit'],
            ['حفظ', 'Save'],
            ['إغلاق', 'Close'],
            ['إلغاء', 'Cancel'],
            ['تطبيق', 'Apply'],
            ['بحث', 'Search'],
            ['ابحث', 'Search'],
            ['خروج', 'Sign Out'],
            ['ريال', 'SAR'],
            ['صفحات', 'pages'],
            ['صفحة', 'page'],
            ['مرفوع', 'Uploaded'],
            ['بانتظار', 'Waiting'],
            ['جديد', 'New'],
            ['جديدة', 'New'],
            ['مكتملة', 'Completed'],
            ['منتهي', 'Completed'],
            ['قيد العمل', 'In Progress'],
            ['مجانًا', 'Free'],
            ['مجانا', 'Free'],
            ['مدفوع', 'Paid'],
            ['غير مدفوع', 'Unpaid'],
            ['بانتظار الدفع', 'Awaiting Payment'],
            ['قيد التنفيذ', 'In Progress'],
            ['قيد المراجعة', 'Under Review'],
            ['مكتمل', 'Completed'],
            ['ملغي', 'Cancelled'],
            ['اختر الألوان', 'Select colors'],
            ['اختر التغليف', 'Select binding'],
            ['اختر التجليد', 'Select binding'],
            ['التغليف', 'Binding'],
            ['التجليد', 'Binding'],
            ['الطباعة', 'Printing'],
            ['الإجمالي', 'Total'],
            ['السعر', 'Price']
        ].sort((a, b) => b[0].length - a[0].length);

        const ignoredTags = new Set(['SCRIPT', 'STYLE', 'TEXTAREA']);

        function translateString(value) {
            if (!value) return value;

            const leading = value.match(/^\s*/)?.[0] ?? '';
            const trailing = value.match(/\s*$/)?.[0] ?? '';
            const core = value.trim();

            if (!core || !/[\u0600-\u06FF]/.test(core)) return value;
            if (dictionary.has(core)) return `${leading}${dictionary.get(core)}${trailing}`;

            let translated = core;
            phraseEntries.forEach(([arabic, english]) => {
                if (translated.includes(arabic)) {
                    translated = translated.split(arabic).join(english);
                }
            });
            safeInlineEntries.forEach(([arabic, english]) => {
                if (translated.includes(arabic)) {
                    translated = translated.split(arabic).join(english);
                }
            });
            return translated === core ? value : `${leading}${translated}${trailing}`;
        }

        function translateTextNode(node) {
            const translated = translateString(node.nodeValue);
            if (translated !== node.nodeValue) {
                node.nodeValue = translated;
            }
        }

        function walk(root) {
            const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
                acceptNode(node) {
                    return ignoredTags.has(node.parentElement?.tagName)
                        ? NodeFilter.FILTER_REJECT
                        : NodeFilter.FILTER_ACCEPT;
                }
            });

            const nodes = [];
            while (walker.nextNode()) nodes.push(walker.currentNode);
            nodes.forEach(translateTextNode);
        }

        function translateAttributes(root) {
            root.querySelectorAll('[placeholder], [title], [aria-label], [alt], [data-label], [value]').forEach((element) => {
                ['placeholder', 'title', 'aria-label', 'alt', 'data-label', 'value'].forEach((attribute) => {
                    const value = element.getAttribute(attribute);
                    if (!value) return;

                    if (attribute === 'value') {
                        const tagName = element.tagName;
                        const type = (element.getAttribute('type') || '').toLowerCase();
                        const isButtonValue = tagName === 'BUTTON' || (tagName === 'INPUT' && ['button', 'submit', 'reset'].includes(type));
                        if (!isButtonValue) return;
                    }

                    const translated = translateString(value);
                    if (translated !== value) {
                        element.setAttribute(attribute, translated);
                        if (attribute === 'value' && 'value' in element && element.value === value) {
                            element.value = translated;
                        }
                    }
                });
            });
        }

        walk(document.body);
        translateAttributes(document.body);

        const observer = new MutationObserver((mutations) => {
            mutations.forEach((mutation) => {
                if (mutation.type === 'characterData') {
                    translateTextNode(mutation.target);
                    return;
                }

                mutation.addedNodes.forEach((node) => {
                    if (node.nodeType === Node.TEXT_NODE) {
                        translateTextNode(node);
                    } else if (node.nodeType === Node.ELEMENT_NODE) {
                        walk(node);
                        translateAttributes(node);
                    }
                });
            });
        });

        observer.observe(document.body, { childList: true, subtree: true, characterData: true });
    })();
</script>

@include('shared.live-page-updates')

<script>
    (() => {
        document.addEventListener('click', (event) => {
            if (event.defaultPrevented || event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;

            const link = event.target.closest('a[href]');
            if (!link || link.hasAttribute('download') || link.matches('[data-delivered-file-download], [data-complete-order-download]')) return;

            const href = link.getAttribute('href')?.trim() || '';
            if (!href || href.startsWith('#') || href.startsWith('javascript:') || href.startsWith('mailto:') || href.startsWith('tel:')) return;

            event.preventDefault();
            window.location.assign(link.href);
        }, true);
    })();
</script>
